theme: jekyll-theme-minimal
title : SISTRAT- Fondecyt 1191282
author : Andrés González Santa Cruz,
name : Andrés González Santa Cruz, Data Analyst of the FONDECYT Project
email : gonzalez.santacruz.andres@gmail.com
github : FONDECYTACC
sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."