---
title: "Codebook For C1 Data"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
---

```{r setup, include=F}
local({r <- getOption("repos")
       r["CRAN"] <- "http://cran.r-project.org" 
       options(repos=r)
})
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = TRUE  # show R code
)
ggplot2::theme_set(ggplot2::theme_bw())
pander::panderOptions("table.split.table", Inf)
#file:///C:/Users/andre/OneDrive/Escritorio/RUTS/codebook%20tutorial.pdf
#https://cran.r-project.org/web/packages/codebook/vignettes/codebook_tutorial.html
if(!require(codebook)){install.packages("codebook")}
if(!require(future)){install.packages("future")}
if(!require(dplyr)){install.packages("dplyr")}
```

```{r prepare_codebook, include=F}
load("G:/Mi unidad/Alvacast/SISTRAT 2019 (github)/6.RData")

codebook_data <- cCONS_C1_df_dup_JUN_2020%>%
dplyr::mutate_at(c('dg_trs_psiq_cie_10_or','x2_dg_trs_psiq_cie_10_or','x3_dg_trs_psiq_cie_10_or','x2_dg_trs_psiq_sub_cie_10_or','x3_dg_trs_psiq_sub_cie_10_or','compromiso_biopsicosocial','pais_nacimiento','nacionalidad','dg_trs_psiq_sub_dsm_iv_or','x2_dg_trs_psiq_sub_dsm_iv_or','x3_dg_trs_psiq_sub_dsm_iv_or','dg_trs_psiq_sub_cie_10_or','etnia_cor_2','motivodeegreso_mod_imp','fecha_ultimo_tratamiento','fecha_ultimo_tratamiento','tiene_menores_de_edad_a_cargo'),~as.factor(.))
# to import an SPSS file from the same folder uncomment and edit the line below
# codebook_data <- rio::import("mydata.sav")
# for Stata
# codebook_data <- rio::import("mydata.dta")
# for CSV
# codebook_data <- rio::import("mydata.csv")

# omit the following lines, if your missing values are already properly labelled
codebook_data <- detect_missing(codebook_data,
    only_labelled = TRUE, # only labelled values are autodetected as
                                   # missing
    negative_values_are_missing = FALSE, # negative values are missing values
    ninety_nine_problems = FALSE,   # 99/999 are missing values, if they
                                   # are more than 5 MAD from the median
    )

# If you are not using formr, the codebook package needs to guess which items
# form a scale. The following line finds item aggregates with names like this:
# scale = scale_1 + scale_2R + scale_3R
# identifying these aggregates allows the codebook function to
# automatically compute reliabilities.
# However, it will not reverse items automatically.
codebook_data <- detect_scales(codebook_data)
```
<br>

In the following Tables and graphics, there is a summary of the variables and docummentation of their characteristics. This high-level summary may permit us find errors on coding, help us to understand missingness and guide us towards an objective, or lead us to more questions. 

<br>

```{r codebook}
codebook_data%>%
  dplyr::select(-consentimiento_informado)%>%
#dplyr::mutate_at(c('fech_ing','fech_egres','fech_nac','fech_egres_knn_imp','fech_egres_imp'),~as.Date(as.character(.))) %>%
codebook()

#fecha_ultimo_tratamiento
#

#Permite exportar los valores de cada variable de tipo factor.
invisible=9
df<- data.frame()
  for (i in names(Filter(is.factor,codebook_data))) { 
        fac<-data.table::data.table(table(codebook_data[i], exclude=NULL))%>% 
            dplyr::mutate(variable=paste0(i),export=paste0(row_number(),".",V1))%>%
            dplyr::select(-V1)%>%
            dplyr::select(variable,export,N)%>%
          dplyr::filter(!grepl("\\.NA",export))
      df_titulo<-data.frame(variable=paste0(i),export=NA, N=999)
      df<- rbind(df,df_titulo,fac)
  }
df<-
  as.data.frame(df)%>%
    dplyr::group_by(variable)%>%
    dplyr::mutate(rn=row_number())%>%
    select(variable,rn,everything())

  guardar_tablas(df, "labels_codebook")

```