<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Data Preparation and Standardization</title>

<script src="Data_prep_C1_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="Data_prep_C1_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="Data_prep_C1_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="Data_prep_C1_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="Data_prep_C1_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="Data_prep_C1_files/navigation-1.1/tabsets.js"></script>
<script src="Data_prep_C1_files/navigation-1.1/codefolding.js"></script>
<link href="Data_prep_C1_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="Data_prep_C1_files/highlightjs-9.12.0/highlight.js"></script>
<script src="Data_prep_C1_files/kePrint-0.0.1/kePrint.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Data Preparation and Standardization</h1>

</div>


<style type="text/css">
.tablelines table, .tablelines td, .tablelines th {
        border: 1px solid black;
        }
.centrado {
    text-align: center;
}
.table.center {
    margin-left:auto; 
    margin-right:auto;
  }
.table_wrapper{
    display: block;
    overflow-x: auto;
    white-space: nowrap;
}
code.r{
  font-size: 8px;
}
body{ /* Normal  */
      text-align: justify;
  }
</style>
<!---

[//]: # (This is <span style="color: red">written in red</span>.)

[//]: # (Hey! Hover the cursor over me and guess what?! :) {: .purple})

[//]: # (I am in <span style="font-family:Papyrus; font-size:4em;">that!</span>)

[//]: #(#687886)

-->
<p>This page will be used to comment and understand the steps, advances and douts about the process of data preparations and standardization of the SISTRAT C1 (Convenio 1) which can be translated to Agreement on Collaboration, Technical Assistance and Transfer of Resources to General Population (“Convenio de Colaboración Técnica y de Transferencia de Recursos para Programa de Población General”). Must note that it does not include Adolescent criminal offenders (C2).</p>
<p>To see the TOP or Profile of Treatment Results (“Perfil de Resultados de Tratamiento”) data preparation, <a href="Data_prep_TOP">go to this webpage</a>.</p>
<p><br></p>
<div id="building-dataset" class="section level2">
<h2>Building dataset</h2>
<p>Define working directories which contains different text files that will be merged, correspondent to the years of the C1 Sistrat.</p>
<pre class="markdown"><code>dir_c1 &lt;-toString(paste0(getwd(),&quot;/Encriptado c1/Personas tratadas c1/&quot;))
dir_top &lt;-toString(paste0(getwd(),&quot;/encriptados TOP/&quot;))
#In my case,
dir_c1 &lt;-toString(paste0(&quot;G:/Mi unidad/Alvacast/SISTRAT 2019 (github)&quot;,&quot;/Encriptado c1/Personas tratadas c1/&quot;))
dir_top &lt;-toString(paste0(&quot;G:/Mi unidad/Alvacast/SISTRAT 2019 (github)&quot;,&quot;/encriptados TOP/&quot;))</code></pre>
<p>Define files in the Directory folder, as long as they have the excel extension and they do not start with ~ (represent a working temporary file in excel)</p>
<pre class="markdown"><code>SISTRAT_c1&lt;-list.files(path=toString(dir_c1), all.files=T, pattern=&quot;^[2].*\\s*txt$&quot;)</code></pre>
<p>SISTRAT_c1 is composed by the following files: * 2010tab-Resultado-20191113 (1).txt * 2011tab -Resultado-20191113.txt * 2012tab-Resultado-20191113.txt * 2013tab-Resultado-20191113.txt * 2014tab-Resultado-20191113.txt * 2015tab-Resultado-20191113.txt * 2016tab-Resultado-20191113.txt * 2017tab-Resultado-20191113.txt * 2018tab-Resultado-20191113.txt * 2019_EneOcttab-Resultado-20191113.txt</p>
<p>Function to <strong>read tab delimited text files</strong>, with UTF-8 encoding and, based on the first 7 letters of its name, assign them an object name.</p>
<pre class="markdown"><code>read_excel_mult &lt;- function(dir, filename) {
  assign(paste0(substr(filename, 1, 7)),read.delim(paste0(dir, filename),
        na.strings=&quot;null&quot;, header = T, fileEncoding=&quot;UTF-8&quot;),envir = .GlobalEnv)
  }</code></pre>
<p><br></p>
<div id="import-datasets" class="section level4">
<h4>Import datasets</h4>
<p>To import the datasets, we apply the previous function to every dataset</p>
<pre class="markdown"><code>for (x in SISTRAT_c1) {
  read_excel_mult(as.character(dir_c1), x)
}</code></pre>
<p><br></p>
</div>
<div id="normalize-datasets" class="section level4">
<h4>Normalize datasets</h4>
<p>Normalize datasets by defining a common name for hash key’s (“HASH_KEY”) and assign them an standardized name.</p>
<pre class="markdown"><code>tab_10_18_mod &lt;- function(x,y) {  get(x) %&gt;% dplyr::rename(&quot;HASH_KEY&quot; = !!names(.[91])) %&gt;%
    as.data.frame() %&gt;% 
    assign(paste0(y, as.character(x)),.,envir = .GlobalEnv)
}
for (i in paste0(c(2010:2018),&quot;tab&quot;)) {tab_10_18_mod(i,y=&quot;c1_&quot;)}

`2019_En` %&gt;% dplyr::rename(&quot;HASH_KEY&quot; = !!names(.[92])) %&gt;%
  as.data.frame() %&gt;% 
  assign(paste0(&quot;c1_&quot;, &quot;2019tab&quot;),.,envir = .GlobalEnv)</code></pre>
<p><br></p>
</div>
<div id="append-the-datasets" class="section level4">
<h4>Append the datasets</h4>
<p>Once normalized column names. Bind every year’s datasets by their rows.</p>
<pre class="markdown"><code>CONS_C1=rbindlist(mget(paste0(&quot;c1_&quot;,c(2010:2019),&quot;tab&quot;)), idcol=&quot;TABLE&quot;, fill=T)
CONS_C1 &lt;- CONS_C1 %&gt;% dplyr::mutate(row=1:nrow(CONS_C1)) %&gt;% dplyr::select(row,everything())</code></pre>
<hr />
<hr />
<hr />
<hr />
<p><br></p>
</div>
</div>
<div id="define-and-format-variable-names" class="section level2">
<h2>Define and format variable names</h2>
<p>Redefine variable names, create a column named <em>ano_bd</em> with the year. Also, it reorder the variables to get the identifiers as the first columns.</p>
<div id="rename-variables" class="section level4">
<h4>Rename Variables</h4>
<pre class="markdown"><code>CONS_C1 %&gt;% 
  dplyr::rename(id=`Codigo.Identificación`) %&gt;%
  dplyr::rename(fech_ing=`Fecha.Ingreso.a.Tratamiento`) %&gt;%
  dplyr::rename(fech_egres=`Fecha.Egreso.de.Tratamiento`) %&gt;%
  dplyr::rename(dias_trat=`Dias.en.Tratamiento`) %&gt;%
  dplyr::rename(eva_consumo=`Evaluación.al.Egreso.Respecto.al.Patrón.de.consumo`) %&gt;%
  dplyr::rename(eva_fam=`Evaluación.al.Egreso.Respecto.a.Situación.Familiar`) %&gt;%
  dplyr::rename(eva_sm=`Evaluación.al.Egreso.Respecto.Salud.Mental`) %&gt;%
  dplyr::rename(eva_fisica=`Evaluación.al.Egreso.Respecto.Salud.Física`) %&gt;%
  dplyr::rename(eva_transgnorma=`Evaluación.al.Egreso.Respecto.Trasgresión.a.la.Norma.Social`) %&gt;% 
  dplyr::rename(eva_relinterp=`Evaluación.al.Egreso.Respecto.Relaciones.Interpersonales`) %&gt;%
  dplyr::rename(eva_ocupacion=`Evaluación.al.Egreso.Respecto.a.Situación.Ocupacional`) %&gt;%
  dplyr::rename(evaluacindelprocesoteraputico=`Evaluación.del.Proceso.Terapéutico`) %&gt;%
  dplyr::rename(nmesesentratamiento=`N.Meses.en.Tratamiento`) %&gt;%
  dplyr::rename(motivodeegreso=`Motivo.de.Egreso`) %&gt;%
  dplyr::rename(tipo_centro=`Tipo.Centro`) %&gt;%
  dplyr::mutate(ano_bd=as.numeric(substr(TABLE,4,7))) %&gt;%
  select(row, TABLE, HASH_KEY,ano_bd, everything()) %&gt;%
  dplyr::arrange(id) %&gt;%
  assign(&quot;CONS_C1_df&quot;,.,envir = .GlobalEnv)</code></pre>
<p>Relevant variables are converted into factors.</p>
<pre class="markdown"><code>CONS_C1_df %&gt;%
  dplyr::mutate(motivodeegreso=as.factor(motivodeegreso)) %&gt;%
  dplyr::mutate(evaluacindelprocesoteraputico=as.factor(evaluacindelprocesoteraputico)) %&gt;%
  dplyr::mutate(eva_consumo=as.factor(eva_consumo)) %&gt;%
  dplyr::mutate(eva_fam=as.factor(eva_fam)) %&gt;%  
  dplyr::mutate(eva_relinterp=as.factor(eva_relinterp)) %&gt;%  
  dplyr::mutate(eva_ocupacion=as.factor(eva_ocupacion)) %&gt;%
  dplyr::mutate(eva_sm=as.factor(eva_sm)) %&gt;%  
  dplyr::mutate(eva_fisica=as.factor(eva_fisica)) %&gt;%
  dplyr::mutate(eva_transgnorma=as.factor(eva_transgnorma)) %&gt;%  
  dplyr::mutate(sexo=as.factor(Sexo)) %&gt;%
  dplyr::mutate(embarazo=as.factor(`X.Se.trata.de.una.mujer.embarazada.`)) %&gt;%
  dplyr::mutate(tipo_de_plan=as.factor(`Tipo.de.Plan`)) %&gt;%  
  dplyr::mutate(tipo_de_programa=as.factor(`Tipo.de.Programa`)) %&gt;%  
  assign(&quot;CONS_C1_df&quot;,.,envir = .GlobalEnv) </code></pre>
<p><br></p>
</div>
<div id="standardize-dates" class="section level4">
<h4>Standardize Dates</h4>
<p><br></p>
<div id="dates-of-admission-and-discharge" class="section level5">
<h5>Dates of admission and discharge</h5>
<p><br></p>
<p>Most of the dates were not formatted equally. When standardized,some cases failed to transform dates, specifically in dates of discharge, which contained 87 cases, while only one case was problematic in admission dates.</p>
<pre class="markdown"><code>CONS_C1_df %&gt;%
  dplyr::mutate(fech_ing= ifelse(row==&quot;14504&quot;, &quot;10/01/2011&quot;,
                          ifelse(row==&quot;88379&quot;, &quot;09/07/2015&quot;, #ACTUALIZACION 2020-01-17: cambio fecha ingreso
                          ifelse(row==&quot;79428&quot;, &quot;09/07/2015&quot;, #ACTUALIZACION 2020-01-17: cambio fecha ingreso             
                                        fech_ing))))  %&gt;%
  dplyr::mutate(fech_ing= lubridate::parse_date_time(fech_ing, c(&quot;%d/%m/%Y&quot;),exact=T)) %&gt;% #un caso falla en ser transformado
  dplyr::mutate(fech_egres_sin_fmt= fech_egres) %&gt;% #me quedo con esta variable por si acaso
  dplyr::mutate(fech_egres= ifelse(row==&quot;36308&quot;, &quot;02/04/2013&quot;,
                            ifelse(row==&quot;14083&quot;, &quot;03/05/2011&quot;,
                            ifelse(row==&quot;6349&quot;, &quot;01/07/2010&quot;,
                            ifelse(row==&quot;42741&quot;, &quot;02/08/2013&quot;,
                            ifelse(row==&quot;8608&quot;,&quot;01/02/2011&quot;,
                            ifelse(row==&quot;11709&quot;,&quot;01/02/2011&quot;,
                            ifelse(row==&quot;40486&quot;,&quot;03/07/2013&quot;,
                            ifelse(row==&quot;42521&quot;,&quot;09/07/2013&quot;,
                            ifelse(row==&quot;5757&quot;, &quot;04/10/2010&quot;, #cambiado
                            ifelse(row==&quot;39507&quot;, &quot;02/07/2013&quot;,
                            ifelse(row==&quot;3195&quot;, &quot;04/10/2010&quot;,
                            ifelse(row==&quot;37845&quot;, &quot;01/07/2013&quot;,
                            ifelse(row==&quot;40180&quot;, &quot;07/08/2013&quot;,
                            ifelse(row==&quot;28008&quot;, &quot;27/11/2012&quot;,
                            ifelse(row==&quot;35971&quot;, &quot;01/03/2013&quot;,
                            ifelse(row==&quot;5172&quot;, &quot;03/05/2011&quot;,
                            ifelse(row==&quot;10415&quot;, &quot;03/05/2011&quot;,
                            ifelse(row==&quot;16385&quot;, &quot;30/08/2011&quot;,
                            ifelse(row==&quot;39932&quot;, &quot;02/08/2013&quot;,
                            ifelse(row==&quot;16983&quot;, &quot;06/09/2011&quot;,
                            ifelse(row==&quot;88379&quot;, &quot;11/04/2016&quot;, #ACTUALIZACION 2020-01-17: cambio fecha egreso
                            ifelse(row==&quot;79428&quot;, &quot;11/04/2016&quot;, #ACTUALIZACION 2020-01-17: cambio fecha egreso
                            ifelse(row==&quot;37004&quot;, &quot;02/08/2013&quot;,fech_egres)))))))))))))))))))))))) %&gt;%
  dplyr::mutate(fech_egres= lubridate::parse_date_time(stringr::str_trim(fech_egres), 
                                                       orders = c(&quot;%d/%m/%Y&quot;, &quot;%d/%m/%y&quot;,&quot;%d%m%Y&quot;),exact=T)) %&gt;%
  dplyr::arrange(desc(ano_bd)) %&gt;% 
  assign(&quot;CONS_C1_df&quot;,.,envir = .GlobalEnv) #87 failed to parse, bajé a 37, y 30 después de quitar espacios</code></pre>
<p>For discharge dates, many cases had different formats. Those had to be transformed once the first formats were traduced (e.g. 30-12-2019 is interpteted first as “%d/%m/%Y” format. If it is not traduced, it interprets in “DD/MM/YY” format (or “%d/%m/%y”). We can see in Table 1 in non-formatted date of discharge (<em>fech_egres_sin_fmt</em>), how was traduced into an plausible discharge date (<em>fech_egres</em>). One criteria is that possibly in many cases, the second and or third 0 would correspond to a month character. On the contrary, “7082013” or “9072013” would be “2013-8-70” and “2013-7-90”, respectively.</p>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:450px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-hover" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Table 1. Problematic cases of dates which required a manual change
</caption>
<thead>
<tr>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Case
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
HASH
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
ID
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Date of Admission
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Date of Discharge
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Date of Discharge (No Format)
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Days in Treatment
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
36,308
</td>
<td style="text-align:center;">
b6373dccc2b0b5ffba42db746b17c692
</td>
<td style="text-align:center;">
CAPE1**051992
</td>
<td style="text-align:center;">
2013-01-29
</td>
<td style="text-align:center;">
2013-04-02
</td>
<td style="text-align:center;">
2013/04/02
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
42,741
</td>
<td style="text-align:center;">
090f64b945afce17900e82eccb8f8da6
</td>
<td style="text-align:center;">
COMO2**091988
</td>
<td style="text-align:center;">
2013-07-02
</td>
<td style="text-align:center;">
2013-08-02
</td>
<td style="text-align:center;">
2082013
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
40,486
</td>
<td style="text-align:center;">
4fc0a1cff37ad152767eb323ed3b43c0
</td>
<td style="text-align:center;">
ELPO2**111980
</td>
<td style="text-align:center;">
2013-05-02
</td>
<td style="text-align:center;">
2013-07-03
</td>
<td style="text-align:center;">
307203
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
42,521
</td>
<td style="text-align:center;">
c668aa3153ea4a1a4435c45557feb80b
</td>
<td style="text-align:center;">
HUDO1**091969
</td>
<td style="text-align:center;">
2013-06-28
</td>
<td style="text-align:center;">
2013-07-09
</td>
<td style="text-align:center;">
9072013
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
39,507
</td>
<td style="text-align:center;">
2f477adf8b5c282660fa16180eb5096d
</td>
<td style="text-align:center;">
LIDO2**031992
</td>
<td style="text-align:center;">
2013-04-29
</td>
<td style="text-align:center;">
2013-07-02
</td>
<td style="text-align:center;">
2072013
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
37,845
</td>
<td style="text-align:center;">
fd919f36ada0b9423cf3acdead577150
</td>
<td style="text-align:center;">
MAZA1**111968
</td>
<td style="text-align:center;">
2013-03-18
</td>
<td style="text-align:center;">
2013-07-01
</td>
<td style="text-align:center;">
1072013
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
40,180
</td>
<td style="text-align:center;">
c8a0c6ccce12e9d3fbc74c06d6a06664
</td>
<td style="text-align:center;">
MIMA2**111973
</td>
<td style="text-align:center;">
2013-05-29
</td>
<td style="text-align:center;">
2013-08-07
</td>
<td style="text-align:center;">
7082013
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
35,971
</td>
<td style="text-align:center;">
132aa32661fbedca4ecdd1e2018c58e3
</td>
<td style="text-align:center;">
PARA1**021977
</td>
<td style="text-align:center;">
2013-01-02
</td>
<td style="text-align:center;">
2013-03-01
</td>
<td style="text-align:center;">
01-03-2013
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
39,932
</td>
<td style="text-align:center;">
c87466931290f44c2c6a89bd127d31e5
</td>
<td style="text-align:center;">
RELA2**011969
</td>
<td style="text-align:center;">
2013-05-22
</td>
<td style="text-align:center;">
2013-08-02
</td>
<td style="text-align:center;">
2082013
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
37,004
</td>
<td style="text-align:center;">
ad7eb82186ec39a61ad29aed61522c2a
</td>
<td style="text-align:center;">
SO-A2**061980
</td>
<td style="text-align:center;">
2013-02-08
</td>
<td style="text-align:center;">
2013-08-02
</td>
<td style="text-align:center;">
2082013
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
28,008
</td>
<td style="text-align:center;">
3d50c479484a18e510d6be8f8a35a1ed
</td>
<td style="text-align:center;">
OMHU1**041990
</td>
<td style="text-align:center;">
2012-06-25
</td>
<td style="text-align:center;">
2012-11-27
</td>
<td style="text-align:center;">
27-11-2012
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
14,083
</td>
<td style="text-align:center;">
68930653a30b13a6f6f7853d6683dff3
</td>
<td style="text-align:center;">
CLFI1**031973
</td>
<td style="text-align:center;">
2011-02-10
</td>
<td style="text-align:center;">
2011-05-03
</td>
<td style="text-align:center;">
30520011
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
14,504
</td>
<td style="text-align:center;">
a7a1fcb4a638a7b194063d95e34320a9
</td>
<td style="text-align:center;">
CLVE2**111966
</td>
<td style="text-align:center;">
2011-01-10
</td>
<td style="text-align:center;">
2011-08-30
</td>
<td style="text-align:center;">
30/08/2011
</td>
<td style="text-align:center;">
232
</td>
</tr>
<tr>
<td style="text-align:center;">
11,709
</td>
<td style="text-align:center;">
52eeb63fbce34e95c7687dd6007efce8
</td>
<td style="text-align:center;">
DASA2**031986
</td>
<td style="text-align:center;">
2008-08-08
</td>
<td style="text-align:center;">
2011-02-01
</td>
<td style="text-align:center;">
01-02-2011
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
10,415
</td>
<td style="text-align:center;">
4aa3462c09ad1a7cc1e6d249f620d715
</td>
<td style="text-align:center;">
PATR1**061986
</td>
<td style="text-align:center;">
2010-04-26
</td>
<td style="text-align:center;">
2011-05-03
</td>
<td style="text-align:center;">
3052011
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
16,385
</td>
<td style="text-align:center;">
1454ce9c37a56516ce054a3513361a66
</td>
<td style="text-align:center;">
RAPA1**051983
</td>
<td style="text-align:center;">
2011-04-18
</td>
<td style="text-align:center;">
2011-08-30
</td>
<td style="text-align:center;">
30/08/20011
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
16,983
</td>
<td style="text-align:center;">
5ebc5439f9db863ff8744778280360db
</td>
<td style="text-align:center;">
SERI1**011960
</td>
<td style="text-align:center;">
2011-05-13
</td>
<td style="text-align:center;">
2011-09-06
</td>
<td style="text-align:center;">
06-09-2011
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
6,349
</td>
<td style="text-align:center;">
9a8fef6d37e8010c477c25db3e5e8455
</td>
<td style="text-align:center;">
CLGO1**101984
</td>
<td style="text-align:center;">
2010-06-17
</td>
<td style="text-align:center;">
2010-07-01
</td>
<td style="text-align:center;">
01707/2010
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
8,608
</td>
<td style="text-align:center;">
52eeb63fbce34e95c7687dd6007efce8
</td>
<td style="text-align:center;">
DASA2**031986
</td>
<td style="text-align:center;">
2008-08-08
</td>
<td style="text-align:center;">
2011-02-01
</td>
<td style="text-align:center;">
01-02-2011
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
5,757
</td>
<td style="text-align:center;">
4485da22c54dbef2c45c61a92b5f7cac
</td>
<td style="text-align:center;">
JAGO1**121972
</td>
<td style="text-align:center;">
2010-05-03
</td>
<td style="text-align:center;">
2010-10-04
</td>
<td style="text-align:center;">
4102010
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
3,195
</td>
<td style="text-align:center;">
07a0a0c984ae3d9dfcd30b55fcb6beb2
</td>
<td style="text-align:center;">
LUME1**091957
</td>
<td style="text-align:center;">
2009-10-07
</td>
<td style="text-align:center;">
2010-10-04
</td>
<td style="text-align:center;">
4102010
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
5,172
</td>
<td style="text-align:center;">
4aa3462c09ad1a7cc1e6d249f620d715
</td>
<td style="text-align:center;">
PATR1**061986
</td>
<td style="text-align:center;">
2010-04-26
</td>
<td style="text-align:center;">
2011-05-03
</td>
<td style="text-align:center;">
3052011
</td>
<td style="text-align:center;">
NA
</td>
</tr>
</tbody>
</table>
</div>
<p><br> As we can see in Table 2, some non-formatted date of discharge (<em>fech_egres_sin_fmt</em>), had insufficient information to traduce into valid dates.</p>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:250px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-hover" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Table 2. Non-interpretable discharge dates
</caption>
<thead>
<tr>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Year
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
case
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
DischargeDate
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
DischargeDate-NoFmt
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
2,011
</td>
<td style="text-align:center;">
12,006
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
5
</td>
</tr>
<tr>
<td style="text-align:center;">
2,011
</td>
<td style="text-align:center;">
12,005
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
5
</td>
</tr>
<tr>
<td style="text-align:center;">
2,011
</td>
<td style="text-align:center;">
12,227
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
25
</td>
</tr>
<tr>
<td style="text-align:center;">
2,010
</td>
<td style="text-align:center;">
8,239
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
15
</td>
</tr>
<tr>
<td style="text-align:center;">
2,010
</td>
<td style="text-align:center;">
9,043
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
5
</td>
</tr>
<tr>
<td style="text-align:center;">
2,010
</td>
<td style="text-align:center;">
2,603
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
20/0/2010
</td>
</tr>
<tr>
<td style="text-align:center;">
2,010
</td>
<td style="text-align:center;">
9,042
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
5
</td>
</tr>
<tr>
<td style="text-align:center;">
2,010
</td>
<td style="text-align:center;">
194
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
15
</td>
</tr>
<tr>
<td style="text-align:center;">
2,010
</td>
<td style="text-align:center;">
9,353
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
25
</td>
</tr>
</tbody>
</table>
</div>
<p><br></p>
<p><strong>UPDATE: 2019-12-11</strong>, had to format this date because it was bad labellled. <code>CONS_C1_df[CONS_C1_df$row=="5757","fech_egres"] &lt;- parse_date_time(str_trim("04/10/2010"), orders = c("%d/%m/%Y"),exact=T)</code>. <strong>UPDATE: 2020-01-17</strong>. Thanks to SENDA’s experts, they provided us with information about a case with missing values in dates of treatment. Had to format this date because it was bad labellled. <code>CONS_C1_df[CONS_C1_df$row=="88379","fech_ing"] &lt;- parse_date_time(str_trim("09/07/2015"), orders = c("%d/%m/%Y"),exact=T)</code>. <strong>UPDATE: 2020-01-17</strong>, had to format this date because it was bad labellled. <code>CONS_C1_df[CONS_C1_df$row=="79428","fech_ing"] &lt;- parse_date_time(str_trim("09/07/2015"), orders = c("%d/%m/%Y"),exact=T)</code>. <strong>UPDATE: 2020-01-17</strong>, had to format this date because it was bad labellled. <code>CONS_C1_df[CONS_C1_df$row=="88379","fech_egres"] &lt;- parse_date_time(str_trim("11/04/2016"), orders = c("%d/%m/%Y"),exact=T)</code>. <strong>UPDATE: 2020-01-17</strong>, had to format this date because it was bad labellled. <code>CONS_C1_df[CONS_C1_df$row=="79428","fech_egres"] &lt;- parse_date_time(str_trim("11/04/2016"), orders = c("%d/%m/%Y"),exact=T)</code>. Still, there is 9752 cases with NULL dates of discharge. <br> <strong><em> </em></strong></p>
</div>
</div>
</div>
<div id="data-cleaning-steps-provided-by-sendas-professional" class="section level2">
<h2>Data Cleaning Steps provided by SENDA’s professional</h2>
<p>This rules were provided by SENDA’s professionals, in order to select adequate data for the analysis.</p>
<p><br></p>
<div id="exclude-not-senda-treatments" class="section level4">
<h4>1. Exclude not SENDA treatments</h4>
<p>In first place, we should discard treatments not provided by SENDA. NULL values correspond to a single HASH key (“72c54d822de128e52f10511f3eb2d19f”, in datasets from 2010 and 2011) that does not have a plan and program either.</p>
<table class="table table-striped table-hover" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Table 3. Treatment Admissions
</caption>
<thead>
<tr>
<th style="text-align:center;">
SENDA
</th>
<th style="text-align:center;">
Frequency
</th>
<th style="text-align:center;">
%
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
No
</td>
<td style="text-align:center;">
7,762
</td>
<td style="text-align:center;">
4.8%
</td>
</tr>
<tr>
<td style="text-align:center;">
Si
</td>
<td style="text-align:center;">
155,382
</td>
<td style="text-align:center;">
95.2%
</td>
</tr>
<tr>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
0%
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> No= Admission under another agreement
</td>
</tr>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> Si= Admission under SENDA agreement
</td>
</tr>
</tfoot>
</table>
<p><br> As we can see in Table 3, around 4.8% of cases had a treatment that could be not part of SENDA’s agreements. The case that did not take part of the SENDA categories eas admitted to a SENDA agreement in 2009/12/10 and was admitted in 2009/12/14. <br> <br></p>
</div>
<div id="explore-the-type-of-plan" class="section level4">
<h4>2. Explore the type of plan</h4>
<p><br></p>
<p>It is necessary to explore if there is any case that may have a treatment under a probation/parole (“libertad vigilada”) plan.<strong>It is necessary to consider the 3 null values in type of plans, equivalent to 2 HASHs.</strong></p>
<pre><code>## Warning: Factor `tipo_de_plan` contains implicit NA, consider using
## `forcats::fct_explicit_na`</code></pre>
<pre><code>## Warning in melt.data.table(., id.vars = c(1:2)): &#39;measure.vars&#39; [count,
## perc] are not all of the same type. By order of hierarchy, the molten data
## value column will be of type &#39;character&#39;. All measure variables not of type
## &#39;character&#39; will be coerced too. Check DETAILS in ?melt.data.table for more on
## coercion.</code></pre>
<table class="table table-striped table-hover" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Table 4. Treatment Plans
</caption>
<thead>
<tr>
<th style="text-align:center;">
Type of Plan
</th>
<th style="text-align:center;">
No SENDA(n)
</th>
<th style="text-align:center;">
No SENDA(%)
</th>
<th style="text-align:center;">
Yes SENDA(n)
</th>
<th style="text-align:center;">
Yes SENDA(%)
</th>
<th style="text-align:center;">
NA (n)
</th>
<th style="text-align:center;">
NA (%)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
CALLE
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
M-PAB
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
109
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
M-PAI
</td>
<td style="text-align:center;">
137
</td>
<td style="text-align:center;">
2%
</td>
<td style="text-align:center;">
10533
</td>
<td style="text-align:center;">
7%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
M-PAI2
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
M-PR
</td>
<td style="text-align:center;">
251
</td>
<td style="text-align:center;">
3%
</td>
<td style="text-align:center;">
7588
</td>
<td style="text-align:center;">
5%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
M-PR2
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
Otro
</td>
<td style="text-align:center;">
1778
</td>
<td style="text-align:center;">
23%
</td>
<td style="text-align:center;">
90
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
PAI LV
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
PG-PAB
</td>
<td style="text-align:center;">
2236
</td>
<td style="text-align:center;">
29%
</td>
<td style="text-align:center;">
54075
</td>
<td style="text-align:center;">
35%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
PG-PAI
</td>
<td style="text-align:center;">
2233
</td>
<td style="text-align:center;">
29%
</td>
<td style="text-align:center;">
66300
</td>
<td style="text-align:center;">
43%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
PG-PR
</td>
<td style="text-align:center;">
1116
</td>
<td style="text-align:center;">
14%
</td>
<td style="text-align:center;">
16599
</td>
<td style="text-align:center;">
11%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
PG PAI 2
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
100%
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> PR= Residential Program
</td>
</tr>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> PAB= Basic Outpatient Program
</td>
</tr>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> PAI= Intensive Outpatient Treatment
</td>
</tr>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> PAI LV= Probation/Parole
</td>
</tr>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> PAI= Intensive Outpatient Treatment
</td>
</tr>
</tfoot>
</table>
<p>Table 4 shows that there is only 1 case in the probation/parole plan. <br> <br></p>
</div>
<div id="changes-in-programs" class="section level4">
<h4>3. Changes in programs</h4>
<p>Change fixed residential, flexible residential and residential programmes into a general population residential program (PG PR). Additionally, flexible residential program cannot be under a probation/parole program.</p>
<p>Must note that there are <strong><em>some plans that have a number 2</em></strong> but they do not contain more than 0% of the total of the datasets. Also there are some plans related to the Treatment of People Living on the Streets Programs (Programa de Tratamiento de Personas en Situación de Calle). <strong><em>For the moment, we are not sure what is the fixed and flexible residential programmes</em></strong>.</p>
<table class="table table-striped table-hover" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Table 5. Contingency Tables of Programs by Plans
</caption>
<thead>
<tr>
<th style="text-align:center;">
Type of Program
</th>
<th style="text-align:center;">
CALLE
</th>
<th style="text-align:center;">
M-PAB
</th>
<th style="text-align:center;">
M-PAI
</th>
<th style="text-align:center;">
M-PAI2
</th>
<th style="text-align:center;">
M-PR
</th>
<th style="text-align:center;">
M-PR2
</th>
<th style="text-align:center;">
Otro
</th>
<th style="text-align:center;">
PAI LV
</th>
<th style="text-align:center;">
PG-PAB
</th>
<th style="text-align:center;">
PG-PAI
</th>
<th style="text-align:center;">
PG-PR
</th>
<th style="text-align:center;">
PG PAI 2
</th>
<th style="text-align:center;">
NA
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Libertad Vigilada
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
Otro
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
890
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
32
</td>
<td style="text-align:center;">
35
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
Programa Alcohol
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
80
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
Programa Calles
</td>
<td style="text-align:center;">
15
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
Programa Específico Mujeres
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
115
</td>
<td style="text-align:center;">
9,741
</td>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
7,590
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
48
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
Programa Población General
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
926
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
246
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
971
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
56,260
</td>
<td style="text-align:center;">
68,368
</td>
<td style="text-align:center;">
17,700
</td>
<td style="text-align:center;">
32
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
3
</td>
</tr>
</tbody>
</table>
<p><br></p>
</div>
<div id="plans-within-alcohol-program" class="section level4">
<h4>4. Plans within Alcohol Program</h4>
<p>If there is a plan within the alcohol program, the plan must be modificated into the general population plan. <br></p>
<p>Every of the PG-PAI, 80 cases in the alcohol program are in the general population plan.</p>
<p><br></p>
</div>
<div id="another-plan" class="section level4">
<h4>5. Another Plan</h4>
<p>If there is any plan correspondent to Another (“Otro”), it changes into a general population program. <br></p>
<p>There are 1868 cases with treatments categorized as Another (“Otro”) plan.</p>
<p><br></p>
</div>
<div id="plan-programs-by-sex" class="section level4">
<h4>6.Plan &amp; Programs by Sex</h4>
<p>Women should be in the M-PAI in they actually are cathegorized in the general population program. <br></p>
<p>As can be seen in Table 6, around 58% of women are in the general population programmes.<strong>Should be removed or changed?</strong></p>
<table class="table table-striped table-hover" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Table 6. Plan by Sex
</caption>
<thead>
<tr>
<th style="text-align:center;">
Plan
</th>
<th style="text-align:center;">
Men (n)
</th>
<th style="text-align:center;">
Men (%)
</th>
<th style="text-align:center;">
Women (n)
</th>
<th style="text-align:center;">
Women (%)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
CALLE
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
0%
</td>
</tr>
<tr>
<td style="text-align:center;">
M-PAB
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
0%
</td>
</tr>
<tr>
<td style="text-align:center;">
M-PAI
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
23%
</td>
</tr>
<tr>
<td style="text-align:center;">
M-PAI2
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
0%
</td>
</tr>
<tr>
<td style="text-align:center;">
M-PR
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
11
</td>
<td style="text-align:center;">
17%
</td>
</tr>
<tr>
<td style="text-align:center;">
M-PR2
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
0%
</td>
</tr>
<tr>
<td style="text-align:center;">
Otro
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1%
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
1%
</td>
</tr>
<tr>
<td style="text-align:center;">
PAI LV
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
PG-PAB
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
38%
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
26%
</td>
</tr>
<tr>
<td style="text-align:center;">
PG-PAI
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
46%
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
31%
</td>
</tr>
<tr>
<td style="text-align:center;">
PG-PR
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
15%
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
1%
</td>
</tr>
<tr>
<td style="text-align:center;">
PG PAI 2
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
0%
</td>
</tr>
<tr>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> PR= Residential Program
</td>
</tr>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> PAB= Basic Outpatient Program
</td>
</tr>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> PAI= Intensive Outpatient Treatment
</td>
</tr>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> PAI LV= Probation/Parole
</td>
</tr>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> PAI= Intensive Outpatient Treatment
</td>
</tr>
</tfoot>
</table>
<p>There are still a few doubts about these criteria: - <strong>Why there are men and women with female gender identity that are in the general population?, (Basic outpatient , intensive outpatient , Residential and Outpatient 2?</strong> - <strong>Should the 2 men and 12 women in M-PAI but with masculine gender identity be in general population (PG PAI)?</strong> - <strong>If in M-PR there is a women with masculine gender identity, should not be in the general population (PG_PR)?</strong></p>
<p><br></p>
</div>
<div id="plan-programs-by-sex-1" class="section level4">
<h4>7.Plan &amp; Programs by Sex</h4>
<p>Only plans “M-PAI”, “M-PR”, “PG-PAB”, “PG-PAI” and “PG-PR” must be preserved. <strong>Considering Table 4, what happens with M-PAB (basic outpatient for women), “Calle”, “PG PAI 2”, “M-PAI2”, “M-PR2”, “PAI LV” or another (“Otro”)? (See Table 4)</strong></p>
<p><br></p>
</div>
<div id="age-of-consumption-begin" class="section level4">
<h4>8.Age of consumption begin</h4>
<p>Treat as missing data the age of consumption begin if it is less than 5 years.</p>
<div id="figure-1.-histogram-of-age-of-consumption-begin" class="section level5">
<h5>Figure 1. Histogram of Age of Consumption Begin</h5>
<pre class="r"><code>  par(mfrow = c(1,2)) 
  hist(CONS_C1_df$Edad.Inicio.Consumo, main=&quot;Distribution of Age\nof Consumption Begin&quot;, 
       xlab=&quot;Age&quot;, ylab=&quot;Freq&quot;, breaks=30, xlim=c(0,80))
  hist(CONS_C1_df$Edad.Inicio.Consumo, main=&quot;Distribution of Age\nof Consumption Begin (zoom)&quot;, 
       xlab=&quot;Age&quot;, ylab=&quot;Freq&quot;, breaks=30, xlim=c(0,10), ylim=c(0,20000))</code></pre>
<p><img src="Data_prep_C1_files/figure-html/bunch_o_figs-1.png" width="768" style="display: block; margin: auto;" /></p>
<p><br>  </p>
<p>There are around 1117 cases with less than 5 years in the consumption begin.</p>
<p> </p>
<p><br></p>
</div>
</div>
<div id="delete-duplicated-cases-same-date-of-admission-and-id" class="section level4">
<h4>9.Delete duplicated cases (same date of admission and ID)</h4>
<p>In this case, we included the HASH-KEY as another and more robust criteria to filter duplicate cases.</p>
<table class="table table-striped table-hover" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Table 7. Repeated cases /Multiple Entrances
</caption>
<thead>
<tr>
<th style="text-align:center;">
</th>
<th style="text-align:center;">
Frequencies
</th>
<th style="text-align:center;">
Percentage
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Repeated
</td>
<td style="text-align:center;">
45,526
</td>
<td style="text-align:center;">
27.9%
</td>
</tr>
<tr>
<td style="text-align:center;">
Unique
</td>
<td style="text-align:center;">
117,620
</td>
<td style="text-align:center;">
72.1%
</td>
</tr>
</tbody>
</table>
<p> </p>
<p>As seen in Table 7, there are more than a quarter of cases that may be replicating across the different datasets.</p>
<p><br>  </p>
</div>
<div id="actual-age" class="section level4">
<h4>10.Actual Age</h4>
<p>Consider as missing age if it is less than 18 years and greater than 90.</p>
<p><br>  </p>
<div id="figure-2.-histogram-of-actual-age" class="section level5">
<h5>Figure 2. Histogram of Actual Age</h5>
<pre class="r"><code>    par(mfrow = c(1,3)) 
    hist(CONS_C1_df$Edad, main=&quot;Distrbution of Age&quot;, 
         xlab=&quot;Age&quot;, ylab=&quot;Freq&quot;, breaks=60)
    hist(CONS_C1_df$Edad, main=&quot;Distrbution of Age (zoom -)&quot;, 
         xlab=&quot;Age&quot;, ylab=&quot;Freq&quot;, breaks=60, xlim=c(0,20), ylim=c(0,2000))
    hist(CONS_C1_df$Edad, main=&quot;Distrbution of Age (zoom +)&quot;, 
         xlab=&quot;Age&quot;, ylab=&quot;Freq&quot;, breaks=60, xlim=c(100,120), ylim=c(0,100)) </code></pre>
<p><img src="Data_prep_C1_files/figure-html/bunch_o_figs2-1.png" width="768" style="display: block; margin: auto;" /></p>
<p><br>  </p>
<pre class="markdown"><code>    CONS_C1_df %&gt;%
      dplyr::filter(Edad&lt;18) %&gt;%
      dplyr::summarise(n())

    CONS_C1_df %&gt;%
      dplyr::filter(Edad&gt;90) %&gt;%
      dplyr::summarise(n())</code></pre>
<p>There are 673 cases with less than 18 years, 24 cases with more than 90 years.</p>
<p>  <br></p>
</div>
</div>
<div id="days-in-treatment" class="section level4">
<h4>11. Days In Treatment</h4>
<p>Consider as missing if cases has more than 1095 days. Do the same for months in treatment.   <br></p>
<div id="figure-3.-histogram-of-days-in-treatment" class="section level5">
<h5>Figure 3. Histogram of Days In Treatment</h5>
<pre class="r"><code>    par(mfrow = c(1,2)) 
    hist(CONS_C1_df$dias_trat, main=&quot;Distribution of\nDays in Treatment&quot;, 
         xlab=&quot;Days&quot;, ylab=&quot;Freq&quot;,xlim=c(-100,4100), breaks=60)
    hist(CONS_C1_df$dias_trat, main=&quot;Distribution of\nDays in Treatment (zoom +)&quot;, 
         xlab=&quot;Days&quot;, ylab=&quot;Freq&quot;, breaks=60, xlim=c(1000,4100), ylim=c(0,2000)) </code></pre>
<p><img src="Data_prep_C1_files/figure-html/bunch_o_figs3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>        #values out of boundaries</code></pre>
<p>As seen in Figure 3, there are 2320 cases with more than 1095 days in treatment. On the other hand, there are 280 cases with negative or no days of treatment. <strong>Should be removed?</strong></p>
<p>  <br></p>
</div>
</div>
<div id="pregnancy-and-sex" class="section level4">
<h4>12. Pregnancy and Sex</h4>
<p>Pregnant men should be considered as missing values. As seen in Table 8, 4 cases of men also reported pregnancy.</p>
<table class="table table-striped table-hover" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Table 8. Pregnancy by Sex
</caption>
<thead>
<tr>
<th style="text-align:center;">
Pregnancy
</th>
<th style="text-align:center;">
Man (n)
</th>
<th style="text-align:center;">
Man (%)
</th>
<th style="text-align:center;">
Women (n)
</th>
<th style="text-align:center;">
Women (%)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
No
</td>
<td style="text-align:center;">
9515
</td>
<td style="text-align:center;">
8%
</td>
<td style="text-align:center;">
43466
</td>
<td style="text-align:center;">
95%
</td>
</tr>
<tr>
<td style="text-align:center;">
Si
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
2430
</td>
<td style="text-align:center;">
5%
</td>
</tr>
<tr>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
107709
</td>
<td style="text-align:center;">
92%
</td>
<td style="text-align:center;">
22
</td>
<td style="text-align:center;">
0%
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> Si= Pregnant
</td>
</tr>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> No= Not Pregnant
</td>
</tr>
</tfoot>
</table>
<p><br></p>
</div>
<div id="type-of-plan-and-sex" class="section level4">
<h4>13. Type of plan and Sex</h4>
<p>See plans M-PR and M-PAI . Check if there are men. Keep if they are, but they identify as women. **This should also be checked reversly?</p>
<p>As seen in table 9, must note that many cases do not answer this question, or what could be more plausible, this question could not be present in previous datasets. This is why we may exclude NA’s (missing values) for the following analysis.</p>
<table class="table table-striped table-hover" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Table 9. Sex by Gender Identity
</caption>
<thead>
<tr>
<th style="text-align:center;">
Gender Identity
</th>
<th style="text-align:center;">
Man (n)
</th>
<th style="text-align:center;">
Man (%)
</th>
<th style="text-align:center;">
Women (n)
</th>
<th style="text-align:center;">
Women (%)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Femenino
</td>
<td style="text-align:center;">
65
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
3249
</td>
<td style="text-align:center;">
7%
</td>
</tr>
<tr>
<td style="text-align:center;">
Masculino
</td>
<td style="text-align:center;">
8012
</td>
<td style="text-align:center;">
7%
</td>
<td style="text-align:center;">
60
</td>
<td style="text-align:center;">
0%
</td>
</tr>
<tr>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
109151
</td>
<td style="text-align:center;">
93%
</td>
<td style="text-align:center;">
42609
</td>
<td style="text-align:center;">
93%
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> Femenino= Feminine
</td>
</tr>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> Masculino= Masculine
</td>
</tr>
</tfoot>
</table>
<p><br>  </p>
<p>In Table 10, can be seen that there are 2 men with a masculine gender identity that are suscribed to M-PAI plan. However, <strong>what happens with the women with masculine gender identity in M-PAI plan?</strong></p>
<table class="table table-striped table-hover" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Table 10. Type of Plan by Gender Identity and Sex
</caption>
<thead>
<tr>
<th style="text-align:center;">
Plan
</th>
<th style="text-align:center;">
Fem.-Men(n)
</th>
<th style="text-align:center;">
Fem.-Men(%)
</th>
<th style="text-align:center;">
Masc.-Men(n)
</th>
<th style="text-align:center;">
Masc.-Men(%)
</th>
<th style="text-align:center;">
Fem.-Women(n)
</th>
<th style="text-align:center;">
Fem.-Women(%)
</th>
<th style="text-align:center;">
Masc.-Women(n)
</th>
<th style="text-align:center;">
Masc.-Women(%)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
M-PAI
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
3%
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
877
</td>
<td style="text-align:center;">
27%
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
20%
</td>
</tr>
<tr>
<td style="text-align:center;">
M-PAI2
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
M-PR
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
3%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
505
</td>
<td style="text-align:center;">
16%
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2%
</td>
</tr>
<tr>
<td style="text-align:center;">
M-PR2
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
Otro
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2%
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
15
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
PG-PAB
</td>
<td style="text-align:center;">
22
</td>
<td style="text-align:center;">
34%
</td>
<td style="text-align:center;">
2688
</td>
<td style="text-align:center;">
34%
</td>
<td style="text-align:center;">
690
</td>
<td style="text-align:center;">
21%
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
32%
</td>
</tr>
<tr>
<td style="text-align:center;">
PG-PAI
</td>
<td style="text-align:center;">
33
</td>
<td style="text-align:center;">
51%
</td>
<td style="text-align:center;">
4060
</td>
<td style="text-align:center;">
51%
</td>
<td style="text-align:center;">
1098
</td>
<td style="text-align:center;">
34%
</td>
<td style="text-align:center;">
28
</td>
<td style="text-align:center;">
47%
</td>
</tr>
<tr>
<td style="text-align:center;">
PG-PR
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
8%
</td>
<td style="text-align:center;">
1212
</td>
<td style="text-align:center;">
15%
</td>
<td style="text-align:center;">
26
</td>
<td style="text-align:center;">
1%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
PG PAI 2
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
0%
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> PR= Residential Program
</td>
</tr>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> PAB= Basic Outpatient Program
</td>
</tr>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> PAI= Intensive Outpatient Treatment
</td>
</tr>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> PAI LV= Probation/Parole
</td>
</tr>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> PAI= Intensive Outpatient Treatment
</td>
</tr>
</tfoot>
</table>
<p><br></p>
</div>
<div id="days-of-treatment" class="section level4">
<h4>14.Days of treatment</h4>
<p>Consider as missing days if theres values 0 and negatives.</p>
<p><br></p>
<p>As shown in Figure 3, there are 280 values 0 or negative.</p>
<pre class="r"><code>    CONS_C1_df %&gt;%
    dplyr::filter(dias_trat&lt;1) %&gt;%
      dplyr::select(-id,-TABLE,-14,-16,-17,-26,-27,-28,-29,-35,-36,-37,-88,-93,-94,-96,-101) %&gt;%
      dplyr::select(row, ano_bd, HASH_KEY, hash_rut_completo, id_mod, dias_trat,fech_ing, fech_egres,tipo_de_plan, tipo_de_programa, 
                    ID.centro,motivodeegreso, everything()) %&gt;%
      head() %&gt;%
 knitr::kable(.,format = &quot;html&quot;, format.args = list(decimal.mark = &quot;.&quot;, big.mark = &quot;,&quot;),
               caption=&quot;Table 11. Cases with lower dates of treatment&quot;,
                 align =rep(&#39;c&#39;, 101))  %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;),font_size = 8) %&gt;%
  scroll_box(width = &quot;100%&quot;, height = &quot;350px&quot;)</code></pre>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:350px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-hover" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Table 11. Cases with lower dates of treatment
</caption>
<thead>
<tr>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
row
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
ano_bd
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
HASH_KEY
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
hash_rut_completo
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
id_mod
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
dias_trat
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
fech_ing
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
fech_egres
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
tipo_de_plan
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
tipo_de_programa
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
ID.centro
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
motivodeegreso
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Nombre.Centro
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
tipo_centro
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Región.del.Centro
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Servicio.de.Salud
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Tipo.de.Programa
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Tipo.de.Plan
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
SENDA
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Dias.en.SENDA
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Edad
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Nombre.Usuario
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Comuna.Residencia
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Origen.de.Ingreso
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
País.Nacimiento
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Nacionalidad
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Etnia
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Estado.Conyugal
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Fecha.Ultimo.Tratamiento
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Sustancia.de.Inicio
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Edad.Inicio.Consumo
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
X.Se.trata.de.una.mujer.embarazada.
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Escolaridad..último.año.cursado.
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Con.Quién.Vive
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Tipo.de.vivienda
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Tenencia.de.la.vivienda
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Sustancia.Principal
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Otras.Sustancias.nº1
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Otras.Sustancias.nº2
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Otras.Sustancias.nº3
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Frecuencia.de.Consumo..Sustancia.Principal.
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Edad.Inicio..Sustancia.Principal.
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Vía.Administración..Sustancia.Principal.
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Diagnóstico.Trs..Consumo.Sustancia
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Diagnóstico.Trs..Psiquiátrico.DSM.IV
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Diagnóstico.Trs..Psiquiátrico.SUB.DSM.IV
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
X2.Diagnóstico.Trs..Psiquiátrico.DSM.IV
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
X2.Diagnóstico.Trs..Psiquiátrico.SUB.DSM.IV
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
X3.Diagnóstico.Trs..Psiquiátrico.DSM.IV
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
X3.Diagnóstico.Trs..Psiquiátrico.SUB.DSM.IV
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Diagnóstico.Trs..Psiquiátrico.CIE.10
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Diagnóstico.Trs..Psiquiátrico.SUB.CIE.10
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
X2.Diagnóstico.Trs..Psiquiátrico.CIE.10
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
X2.Diagnóstico.Trs..Psiquiátrico.SUB.CIE.10
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
X3.Diagnóstico.Trs..Psiquiátrico.CIE.10
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
X3.Diagnóstico.Trs..Psiquiátrico.SUB.CIE.10
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Diagnóstico.Trs..Físico
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Otros.Problemas.de.Atención.de.Salud.Mental
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Compromiso.Biopsicosocial
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
DIAGNOSTICO.GLOBAL.DE.NECESIDADES.DE.INTEGRACION.SOCIAL
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
DIAGNOSTICO.DE.NECESIDADES.DE.INTEGRACIóN.SOCIAL.EN.CAPITAL.HUMANO
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
DIAGNOSTICO.DE.NECESIDADES.DE.INTEGRACIóN.SOCIAL.EN.CAPITAL.FISICO
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
DIAGNOSTICO.DE.NECESIDADES.DE.INTEGRACIóN.SOCIAL.EN.CAPITAL.SOCIAL
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Fecha.Ingreso.a.Convenio.SENDA
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Usuario.de.Tribunales..Tratamiento.Drogas
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Consentimiento.Informado
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Tipo.Centro.Derivación
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
evaluacindelprocesoteraputico
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
eva_consumo
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
eva_fam
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
eva_relinterp
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
eva_ocupacion
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
eva_sm
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
eva_fisica
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
eva_transgnorma
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Diagnóstico.Trastorno.Psiquiátrico.CIE.10.al.Egreso
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
DIAGNOSTICO.GLOBAL.DE.NECESIDADES.DE.INTEGRACION.SOCIAL.1
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
DIAGNOSTICO.DE.NECESIDADES.DE.INTEGRACIóN.SOCIAL.EN.CAPITAL.HUMANO.1
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
DIAGNOSTICO.DE.NECESIDADES.DE.INTEGRACIóN.SOCIAL.EN.CAPITAL.FISICO.1
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
DIAGNOSTICO.DE.NECESIDADES.DE.INTEGRACIóN.SOCIAL.EN.CAPITAL.SOCIAL.1
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Motivo.de.egreso.Alta.Administrativa
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Consorcio
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Ha.estado.embarazada.egreso.
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
sexo
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
embarazo
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
ano_nac
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
53,692
</td>
<td style="text-align:center;">
2,014
</td>
<td style="text-align:center;">
44e3de7dae9efc5f37695d7bef2a19ee
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
CAGA2**121982
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2014-01-28
</td>
<td style="text-align:center;">
2014-01-28
</td>
<td style="text-align:center;">
M-PR
</td>
<td style="text-align:center;">
Programa Específico Mujeres
</td>
<td style="text-align:center;">
159
</td>
<td style="text-align:center;">
Abandono
</td>
<td style="text-align:center;">
Comunidad Terapeutica Crem (Hogares Crem)
</td>
<td style="text-align:center;">
privado
</td>
<td style="text-align:center;">
METROPOLITANA
</td>
<td style="text-align:center;">
Metropolitano Oriente
</td>
<td style="text-align:center;">
Programa Específico Mujeres
</td>
<td style="text-align:center;">
M-PR
</td>
<td style="text-align:center;">
Si
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
36
</td>
<td style="text-align:center;">
OCULTO
</td>
<td style="text-align:center;">
MACUL
</td>
<td style="text-align:center;">
Otro Centro Tratamiento Drogas
</td>
<td style="text-align:center;">
Chile
</td>
<td style="text-align:center;">
Chile
</td>
<td style="text-align:center;">
No pertenece
</td>
<td style="text-align:center;">
Soltero
</td>
<td style="text-align:center;">
último 6 meses
</td>
<td style="text-align:center;">
Alcohol
</td>
<td style="text-align:center;">
13
</td>
<td style="text-align:center;">
No
</td>
<td style="text-align:center;">
UNIVERSITARIA INCOMPLETA
</td>
<td style="text-align:center;">
Únicamente con hijos y padres o familia de origen
</td>
<td style="text-align:center;">
Casa
</td>
<td style="text-align:center;">
Allegado
</td>
<td style="text-align:center;">
Alcohol
</td>
<td style="text-align:center;">
Cocaína
</td>
<td style="text-align:center;">
Marihuana
</td>
<td style="text-align:center;">
Hongos
</td>
<td style="text-align:center;">
4-6 días - semana
</td>
<td style="text-align:center;">
13
</td>
<td style="text-align:center;">
Oral (bebida o comida)
</td>
<td style="text-align:center;">
Dependencia
</td>
<td style="text-align:center;">
En estudio
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
En estudio
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Sin trastorno
</td>
<td style="text-align:center;">
Abuso Sexual
</td>
<td style="text-align:center;">
Severo
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
28/01/2014
</td>
<td style="text-align:center;">
No
</td>
<td style="text-align:center;">
Si
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Logro M?mo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Opazo y Compañia Ltda.
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Mujer
</td>
<td style="text-align:center;">
No
</td>
<td style="text-align:center;">
1,982
</td>
</tr>
<tr>
<td style="text-align:center;">
53,553
</td>
<td style="text-align:center;">
2,014
</td>
<td style="text-align:center;">
86abe004a5c39f635f562c49d2329f7d
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
JODI2**021993
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2014-01-06
</td>
<td style="text-align:center;">
2014-01-06
</td>
<td style="text-align:center;">
Otro
</td>
<td style="text-align:center;">
Programa Específico Mujeres
</td>
<td style="text-align:center;">
219
</td>
<td style="text-align:center;">
Alta Admnistrativa
</td>
<td style="text-align:center;">
Comunidad Terapeutica Romeral (Dianova Mujeres Maule)
</td>
<td style="text-align:center;">
privado
</td>
<td style="text-align:center;">
DEL MAULE
</td>
<td style="text-align:center;">
Maule
</td>
<td style="text-align:center;">
Programa Específico Mujeres
</td>
<td style="text-align:center;">
Otro
</td>
<td style="text-align:center;">
Si
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
26
</td>
<td style="text-align:center;">
OCULTO
</td>
<td style="text-align:center;">
TALCA
</td>
<td style="text-align:center;">
Otros de la Red de Salud General Público
</td>
<td style="text-align:center;">
Chile
</td>
<td style="text-align:center;">
Chile
</td>
<td style="text-align:center;">
No pertenece
</td>
<td style="text-align:center;">
Soltero
</td>
<td style="text-align:center;">
último 6 meses
</td>
<td style="text-align:center;">
Marihuana
</td>
<td style="text-align:center;">
13
</td>
<td style="text-align:center;">
No
</td>
<td style="text-align:center;">
BASICA INCOMPLETA
</td>
<td style="text-align:center;">
Únicamente con padres o familia de origen
</td>
<td style="text-align:center;">
Casa
</td>
<td style="text-align:center;">
Allegado
</td>
<td style="text-align:center;">
Pasta Base
</td>
<td style="text-align:center;">
Marihuana
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Todos los días
</td>
<td style="text-align:center;">
15
</td>
<td style="text-align:center;">
Fumada o Pulmonar (aspiración de gases o vapores)
</td>
<td style="text-align:center;">
Dependencia
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
En estudio
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
ETS
</td>
<td style="text-align:center;">
Explotaci?omercial Sexual
</td>
<td style="text-align:center;">
Moderado
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
06/01/2014
</td>
<td style="text-align:center;">
No
</td>
<td style="text-align:center;">
Si
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Logro M?mo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
ONG. Dianova Chile
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Mujer
</td>
<td style="text-align:center;">
No
</td>
<td style="text-align:center;">
1,993
</td>
</tr>
<tr>
<td style="text-align:center;">
53,402
</td>
<td style="text-align:center;">
2,014
</td>
<td style="text-align:center;">
ac3c9557b7a403430b8058e3099fa221
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
PAAL1**071976
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2014-01-27
</td>
<td style="text-align:center;">
2014-01-27
</td>
<td style="text-align:center;">
Otro
</td>
<td style="text-align:center;">
Programa Población General
</td>
<td style="text-align:center;">
303
</td>
<td style="text-align:center;">
Alta Admnistrativa
</td>
<td style="text-align:center;">
CTR Nehuen (Residencial Melipilla)
</td>
<td style="text-align:center;">
publico
</td>
<td style="text-align:center;">
METROPOLITANA
</td>
<td style="text-align:center;">
Metropolitano Occidente
</td>
<td style="text-align:center;">
Programa Población General
</td>
<td style="text-align:center;">
Otro
</td>
<td style="text-align:center;">
Si
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
43
</td>
<td style="text-align:center;">
OCULTO
</td>
<td style="text-align:center;">
MELIPILLA
</td>
<td style="text-align:center;">
Consulta Espontánea
</td>
<td style="text-align:center;">
Chile
</td>
<td style="text-align:center;">
Chile
</td>
<td style="text-align:center;">
No pertenece
</td>
<td style="text-align:center;">
Casado
</td>
<td style="text-align:center;">
último 12 meses
</td>
<td style="text-align:center;">
Alcohol
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
BASICA COMPLETA
</td>
<td style="text-align:center;">
Únicamente con la pareja e hijos
</td>
<td style="text-align:center;">
Mediagua
</td>
<td style="text-align:center;">
Propia
</td>
<td style="text-align:center;">
Pasta Base
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
2-3 días - semana
</td>
<td style="text-align:center;">
24
</td>
<td style="text-align:center;">
Fumada o Pulmonar (aspiración de gases o vapores)
</td>
<td style="text-align:center;">
Dependencia
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
En estudio
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
En estudio
</td>
<td style="text-align:center;">
Sin otros problemas de salud mental
</td>
<td style="text-align:center;">
Severo
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
27/01/2014
</td>
<td style="text-align:center;">
No
</td>
<td style="text-align:center;">
Si
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Logro M?mo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
SERVICIO DE SALUD METROPOLITANO OCCIDENTE
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Hombre
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
1,976
</td>
</tr>
<tr>
<td style="text-align:center;">
36,706
</td>
<td style="text-align:center;">
2,013
</td>
<td style="text-align:center;">
b24c50c72c85669ea416ec86b3b11681
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
ALAC1**031981
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2013-02-04
</td>
<td style="text-align:center;">
2013-02-04
</td>
<td style="text-align:center;">
PG-PAI
</td>
<td style="text-align:center;">
Programa Población General
</td>
<td style="text-align:center;">
148
</td>
<td style="text-align:center;">
Abandono
</td>
<td style="text-align:center;">
COSAM Quilicura
</td>
<td style="text-align:center;">
publico
</td>
<td style="text-align:center;">
METROPOLITANA
</td>
<td style="text-align:center;">
Metropolitano Norte
</td>
<td style="text-align:center;">
Programa Población General
</td>
<td style="text-align:center;">
PG-PAI
</td>
<td style="text-align:center;">
No
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
38
</td>
<td style="text-align:center;">
OCULTO
</td>
<td style="text-align:center;">
QUILICURA
</td>
<td style="text-align:center;">
Consulta Espontánea
</td>
<td style="text-align:center;">
Chile
</td>
<td style="text-align:center;">
Chile
</td>
<td style="text-align:center;">
No pertenece
</td>
<td style="text-align:center;">
Soltero
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Marihuana
</td>
<td style="text-align:center;">
17
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
MEDIA COMPLETA
</td>
<td style="text-align:center;">
Únicamente con pareja
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Pasta Base
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
4-6 días - semana
</td>
<td style="text-align:center;">
28
</td>
<td style="text-align:center;">
Fumada o Pulmonar (aspiración de gases o vapores)
</td>
<td style="text-align:center;">
Dependencia
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
En estudio
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Sin trastorno
</td>
<td style="text-align:center;">
Otros
</td>
<td style="text-align:center;">
Severo
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
No
</td>
<td style="text-align:center;">
Si
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Logro M?mo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
SERVICIO DE SALUD METROPOLITANO NORTE
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Hombre
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
1,981
</td>
</tr>
<tr>
<td style="text-align:center;">
36,713
</td>
<td style="text-align:center;">
2,013
</td>
<td style="text-align:center;">
c4f4e254f4e5224db6b81d5f0fdddb6e
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
ALAG1**021994
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2013-02-06
</td>
<td style="text-align:center;">
2013-02-06
</td>
<td style="text-align:center;">
PG-PAI
</td>
<td style="text-align:center;">
Programa Población General
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Derivación
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Programa Población General
</td>
<td style="text-align:center;">
PG-PAI
</td>
<td style="text-align:center;">
Si
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
OCULTO
</td>
<td style="text-align:center;">
SANTIAGO CENTRO
</td>
<td style="text-align:center;">
Otros de la Red de Salud General Privado
</td>
<td style="text-align:center;">
Chile
</td>
<td style="text-align:center;">
Chile
</td>
<td style="text-align:center;">
Mapuche
</td>
<td style="text-align:center;">
Casado
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Alcohol
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
BASICA COMPLETA
</td>
<td style="text-align:center;">
Solo
</td>
<td style="text-align:center;">
Casa
</td>
<td style="text-align:center;">
Arrienda
</td>
<td style="text-align:center;">
Alcohol
</td>
<td style="text-align:center;">
Marihuana
</td>
<td style="text-align:center;">
Cocaína
</td>
<td style="text-align:center;">
Pasta Base
</td>
<td style="text-align:center;">
Todos los días
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
Fumada o Pulmonar (aspiración de gases o vapores)
</td>
<td style="text-align:center;">
Dependencia
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
En estudio
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Otras Enfermedades o Condiciones de Riesgo Vital
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Severo
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
06/02/2013
</td>
<td style="text-align:center;">
No
</td>
<td style="text-align:center;">
Si
</td>
<td style="text-align:center;">
Otro Centro
</td>
<td style="text-align:center;">
Logro M?mo
</td>
<td style="text-align:center;">
Logro Alto
</td>
<td style="text-align:center;">
Logro Alto
</td>
<td style="text-align:center;">
Logro Alto
</td>
<td style="text-align:center;">
Logro Alto
</td>
<td style="text-align:center;">
Logro Alto
</td>
<td style="text-align:center;">
Logro Intermedio
</td>
<td style="text-align:center;">
Logro Alto
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Hombre
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
1,994
</td>
</tr>
<tr>
<td style="text-align:center;">
45,004
</td>
<td style="text-align:center;">
2,013
</td>
<td style="text-align:center;">
ace460ae4527071c9039dc91dfd58092
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
ALCA1**121956
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2013-10-14
</td>
<td style="text-align:center;">
2013-10-14
</td>
<td style="text-align:center;">
PG-PAB
</td>
<td style="text-align:center;">
Programa Población General
</td>
<td style="text-align:center;">
241
</td>
<td style="text-align:center;">
Alta Admnistrativa
</td>
<td style="text-align:center;">
CRS La Florida
</td>
<td style="text-align:center;">
publico
</td>
<td style="text-align:center;">
METROPOLITANA
</td>
<td style="text-align:center;">
Metropolitano Sur Oriente
</td>
<td style="text-align:center;">
Programa Población General
</td>
<td style="text-align:center;">
PG-PAB
</td>
<td style="text-align:center;">
No
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
62
</td>
<td style="text-align:center;">
OCULTO
</td>
<td style="text-align:center;">
LA FLORIDA
</td>
<td style="text-align:center;">
Estab. de APS
</td>
<td style="text-align:center;">
Chile
</td>
<td style="text-align:center;">
Chile
</td>
<td style="text-align:center;">
No pertenece
</td>
<td style="text-align:center;">
Casado
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Alcohol
</td>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
MEDIA INCOMPLETA
</td>
<td style="text-align:center;">
Únicamente con la pareja e hijos
</td>
<td style="text-align:center;">
Departamento
</td>
<td style="text-align:center;">
Propia
</td>
<td style="text-align:center;">
Alcohol
</td>
<td style="text-align:center;">
Cocaína
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
2-3 días - semana
</td>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
Oral (bebida o comida)
</td>
<td style="text-align:center;">
Consumo Perjudicial
</td>
<td style="text-align:center;">
En estudio
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
En estudio
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
En estudio
</td>
<td style="text-align:center;">
Sin otros problemas de salud mental
</td>
<td style="text-align:center;">
Moderado
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
No
</td>
<td style="text-align:center;">
No
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Logro M?mo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
Logro Mínimo
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
SERVICIO DE SALUD METROPOLITANO SUR ORIENTE
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
Hombre
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
1,956
</td>
</tr>
</tbody>
</table>
</div>
<p><br></p>
</div>
<div id="age-of-consumption-begin-and-actual-age" class="section level4">
<h4>15.Age of Consumption Begin and Actual Age</h4>
<p>Consider the age of consumption begin as missing data if it is greater than the actual age. <br></p>
<p>In 780 cases the age of consumption begin is greater than the actual age.</p>
<p><br></p>
<pre class="r"><code>CONS_C1_df %&gt;% dplyr::mutate(edad_inicio_cons= ifelse(Edad.Inicio.Consumo&gt;Edad, 1, 0)) %&gt;% dplyr::filter(edad_inicio_cons==1) %&gt;%
  dplyr::select(row, HASH_KEY, ano_bd, id_mod, Edad.Inicio.Consumo,Edad) %&gt;% 
  head(50) %&gt;%
 knitr::kable(.,format = &quot;html&quot;, format.args = list(decimal.mark = &quot;.&quot;, big.mark = &quot;,&quot;),
               caption=&quot;Table 12. Cases with age of consumption begin greater than the actual age&quot;,
                 align =rep(&#39;c&#39;, 101))  %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;),font_size = 8) %&gt;%
  scroll_box(width = &quot;100%&quot;, height = &quot;350px&quot;)</code></pre>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:350px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-hover" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Table 12. Cases with age of consumption begin greater than the actual age
</caption>
<thead>
<tr>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
row
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
HASH_KEY
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
ano_bd
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
id_mod
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Edad.Inicio.Consumo
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Edad
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
155,268
</td>
<td style="text-align:center;">
fb74493f56becc488867fe53c5573a08
</td>
<td style="text-align:center;">
2,019
</td>
<td style="text-align:center;">
ALAL2**012001
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
18
</td>
</tr>
<tr>
<td style="text-align:center;">
161,209
</td>
<td style="text-align:center;">
2a33829bf3464ee50d4c8c5087a81093
</td>
<td style="text-align:center;">
2,019
</td>
<td style="text-align:center;">
CORU2**021992
</td>
<td style="text-align:center;">
32
</td>
<td style="text-align:center;">
27
</td>
</tr>
<tr>
<td style="text-align:center;">
150,494
</td>
<td style="text-align:center;">
69c9e351e5132a9b487eaeaea44c0c77
</td>
<td style="text-align:center;">
2,019
</td>
<td style="text-align:center;">
GOMI1**062000
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
19
</td>
</tr>
<tr>
<td style="text-align:center;">
158,818
</td>
<td style="text-align:center;">
d6d3a38f49580254e4a9a876b2209b29
</td>
<td style="text-align:center;">
2,019
</td>
<td style="text-align:center;">
ISAM1**062001
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
18
</td>
</tr>
<tr>
<td style="text-align:center;">
151,947
</td>
<td style="text-align:center;">
910ad076dd1e17a321519f65c5feaa99
</td>
<td style="text-align:center;">
2,019
</td>
<td style="text-align:center;">
JALI1**061979
</td>
<td style="text-align:center;">
52
</td>
<td style="text-align:center;">
40
</td>
</tr>
<tr>
<td style="text-align:center;">
160,567
</td>
<td style="text-align:center;">
4935ae99848d64148eb2f1a0230c4ebb
</td>
<td style="text-align:center;">
2,019
</td>
<td style="text-align:center;">
KATE2**072001
</td>
<td style="text-align:center;">
24
</td>
<td style="text-align:center;">
18
</td>
</tr>
<tr>
<td style="text-align:center;">
159,445
</td>
<td style="text-align:center;">
a0eee7839dc689824f91b86db156f82f
</td>
<td style="text-align:center;">
2,019
</td>
<td style="text-align:center;">
MAES2**072001
</td>
<td style="text-align:center;">
22
</td>
<td style="text-align:center;">
18
</td>
</tr>
<tr>
<td style="text-align:center;">
153,734
</td>
<td style="text-align:center;">
7d92e6e8d55a12c1b308c78dbad0f5b9
</td>
<td style="text-align:center;">
2,019
</td>
<td style="text-align:center;">
MAPE1**031995
</td>
<td style="text-align:center;">
29
</td>
<td style="text-align:center;">
24
</td>
</tr>
<tr>
<td style="text-align:center;">
148,287
</td>
<td style="text-align:center;">
e586f94b6247f0e208a906f97f2420f2
</td>
<td style="text-align:center;">
2,019
</td>
<td style="text-align:center;">
NECU1**052000
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
19
</td>
</tr>
<tr>
<td style="text-align:center;">
146,598
</td>
<td style="text-align:center;">
1d91d6b2b75fe7a4d8e2a8dfebcfa16c
</td>
<td style="text-align:center;">
2,019
</td>
<td style="text-align:center;">
NELA1**121999
</td>
<td style="text-align:center;">
54
</td>
<td style="text-align:center;">
19
</td>
</tr>
<tr>
<td style="text-align:center;">
159,705
</td>
<td style="text-align:center;">
a6929b6c7987cce64b0ca1b3f3299bea
</td>
<td style="text-align:center;">
2,019
</td>
<td style="text-align:center;">
ROCO2**072001
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
18
</td>
</tr>
<tr>
<td style="text-align:center;">
160,788
</td>
<td style="text-align:center;">
f90dd528fbe2005a3a3cf88e4f873c83
</td>
<td style="text-align:center;">
2,019
</td>
<td style="text-align:center;">
RUTR2**051997
</td>
<td style="text-align:center;">
24
</td>
<td style="text-align:center;">
22
</td>
</tr>
<tr>
<td style="text-align:center;">
131,749
</td>
<td style="text-align:center;">
9018b21f72370bdeca005ab540d7c7be
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
ALNE1**101999
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
127,314
</td>
<td style="text-align:center;">
fc87d7f86b4e9f568fb50eccb29f3891
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
ANAR1**041999
</td>
<td style="text-align:center;">
24
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
136,733
</td>
<td style="text-align:center;">
07402f400b254ee4662b8a831365612b
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
DIJI1**051992
</td>
<td style="text-align:center;">
34
</td>
<td style="text-align:center;">
27
</td>
</tr>
<tr>
<td style="text-align:center;">
138,430
</td>
<td style="text-align:center;">
445bfb8e194056cb920c163d851c3f92
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
ELCA1**052000
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
19
</td>
</tr>
<tr>
<td style="text-align:center;">
125,808
</td>
<td style="text-align:center;">
578ae693be289de023125ddd2777dd1c
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
GARO1**012015
</td>
<td style="text-align:center;">
15
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
144,205
</td>
<td style="text-align:center;">
69c9e351e5132a9b487eaeaea44c0c77
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
GOMI1**062000
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
19
</td>
</tr>
<tr>
<td style="text-align:center;">
125,800
</td>
<td style="text-align:center;">
8d2dfe24c7a24d541a13b4e82b82eede
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
HEAV1**112014
</td>
<td style="text-align:center;">
13
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
131,633
</td>
<td style="text-align:center;">
e0a8c5bbde98b9ed30a52230a7a8b0cb
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
JACE2**061999
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
142,720
</td>
<td style="text-align:center;">
0c9be3e89c1a7576227d2204aada9c24
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
JUVA1**111993
</td>
<td style="text-align:center;">
26
</td>
<td style="text-align:center;">
25
</td>
</tr>
<tr>
<td style="text-align:center;">
126,276
</td>
<td style="text-align:center;">
9b2836d1a04bffaf371d93392573f692
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
MAGU2**051996
</td>
<td style="text-align:center;">
43
</td>
<td style="text-align:center;">
23
</td>
</tr>
<tr>
<td style="text-align:center;">
129,532
</td>
<td style="text-align:center;">
b24908c527faa1b7bd5a267d5dcabd45
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
MAHE2**091999
</td>
<td style="text-align:center;">
62
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
131,012
</td>
<td style="text-align:center;">
eaf995cb33d947ef6b637e0f89907f96
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
MIPE1**091999
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
127,827
</td>
<td style="text-align:center;">
6fc3007c689e78c3a6af220449514b4e
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
MYLO2**051986
</td>
<td style="text-align:center;">
46
</td>
<td style="text-align:center;">
33
</td>
</tr>
<tr>
<td style="text-align:center;">
140,084
</td>
<td style="text-align:center;">
e586f94b6247f0e208a906f97f2420f2
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
NECU1**052000
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
19
</td>
</tr>
<tr>
<td style="text-align:center;">
133,368
</td>
<td style="text-align:center;">
1d91d6b2b75fe7a4d8e2a8dfebcfa16c
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
NELA1**121999
</td>
<td style="text-align:center;">
54
</td>
<td style="text-align:center;">
19
</td>
</tr>
<tr>
<td style="text-align:center;">
130,850
</td>
<td style="text-align:center;">
865d8750fff6ca0711f52527bcd70b96
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
PAAV2**101997
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
22
</td>
</tr>
<tr>
<td style="text-align:center;">
129,149
</td>
<td style="text-align:center;">
ac8234f0a33399c702103d076a9a8de5
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
REVA2**081999
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
132,807
</td>
<td style="text-align:center;">
2174b5058b56e4471af11248a73f215b
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
ROVE1**121999
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
19
</td>
</tr>
<tr>
<td style="text-align:center;">
125,944
</td>
<td style="text-align:center;">
711029aaa5f478f2c55223d285eb84fe
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
SHMA1**082013
</td>
<td style="text-align:center;">
15
</td>
<td style="text-align:center;">
6
</td>
</tr>
<tr>
<td style="text-align:center;">
127,280
</td>
<td style="text-align:center;">
45fce40da4dfc892ba5d4154f8d6b5b6
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
SOVA2**121998
</td>
<td style="text-align:center;">
46
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
125,778
</td>
<td style="text-align:center;">
ad16844e62fd0a0db5ddd59ccffccbf6
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
SUUB2**102013
</td>
<td style="text-align:center;">
26
</td>
<td style="text-align:center;">
6
</td>
</tr>
<tr>
<td style="text-align:center;">
127,320
</td>
<td style="text-align:center;">
5ca64697dd399116abdd351906e52ab1
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
YESA1**031999
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
136,457
</td>
<td style="text-align:center;">
744991c3ca5e12e87f2a7925d254e5f6
</td>
<td style="text-align:center;">
2,018
</td>
<td style="text-align:center;">
YOBO2**022000
</td>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
19
</td>
</tr>
<tr>
<td style="text-align:center;">
125,184
</td>
<td style="text-align:center;">
9018b21f72370bdeca005ab540d7c7be
</td>
<td style="text-align:center;">
2,017
</td>
<td style="text-align:center;">
ALNE1**101999
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
116,020
</td>
<td style="text-align:center;">
fc87d7f86b4e9f568fb50eccb29f3891
</td>
<td style="text-align:center;">
2,017
</td>
<td style="text-align:center;">
ANAR1**041999
</td>
<td style="text-align:center;">
24
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
106,706
</td>
<td style="text-align:center;">
c51ce03a395b620b21a70b0d028a77e6
</td>
<td style="text-align:center;">
2,017
</td>
<td style="text-align:center;">
ANMA1**031996
</td>
<td style="text-align:center;">
27
</td>
<td style="text-align:center;">
23
</td>
</tr>
<tr>
<td style="text-align:center;">
120,750
</td>
<td style="text-align:center;">
bde31338de6a454e11a31da13e9aa8ee
</td>
<td style="text-align:center;">
2,017
</td>
<td style="text-align:center;">
BAGA2**041996
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
23
</td>
</tr>
<tr>
<td style="text-align:center;">
106,134
</td>
<td style="text-align:center;">
68a1abebf175673e62b97b65fde63b50
</td>
<td style="text-align:center;">
2,017
</td>
<td style="text-align:center;">
BRHE1**092015
</td>
<td style="text-align:center;">
15
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
119,326
</td>
<td style="text-align:center;">
4908c125c91bed71becbd7cf1077e5b2
</td>
<td style="text-align:center;">
2,017
</td>
<td style="text-align:center;">
CALU2**071999
</td>
<td style="text-align:center;">
24
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
105,458
</td>
<td style="text-align:center;">
2cdd842e8b1102992ff2c060e7b46178
</td>
<td style="text-align:center;">
2,017
</td>
<td style="text-align:center;">
CASA1**122014
</td>
<td style="text-align:center;">
18
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
105,847
</td>
<td style="text-align:center;">
87afef689812b1ad6f576f0e83e5c963
</td>
<td style="text-align:center;">
2,017
</td>
<td style="text-align:center;">
DABU1**032015
</td>
<td style="text-align:center;">
14
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
107,001
</td>
<td style="text-align:center;">
31d3a088c8730a02c4ef7239a02e511f
</td>
<td style="text-align:center;">
2,017
</td>
<td style="text-align:center;">
DIBU2**041996
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
23
</td>
</tr>
<tr>
<td style="text-align:center;">
105,661
</td>
<td style="text-align:center;">
0d5782868d35d58892a0f938813f7608
</td>
<td style="text-align:center;">
2,017
</td>
<td style="text-align:center;">
EDHO1**052015
</td>
<td style="text-align:center;">
17
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
106,644
</td>
<td style="text-align:center;">
2817347e37b21d9ff166af0685b417ff
</td>
<td style="text-align:center;">
2,017
</td>
<td style="text-align:center;">
ENSA1**031996
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
23
</td>
</tr>
<tr>
<td style="text-align:center;">
108,082
</td>
<td style="text-align:center;">
d9e020a08875ef763ce0c3e06cbf1b9d
</td>
<td style="text-align:center;">
2,017
</td>
<td style="text-align:center;">
ERVA1**081995
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
24
</td>
</tr>
<tr>
<td style="text-align:center;">
124,962
</td>
<td style="text-align:center;">
99246ebba3341f26ce047e32d9c3742b
</td>
<td style="text-align:center;">
2,017
</td>
<td style="text-align:center;">
FEJA1**121999
</td>
<td style="text-align:center;">
36
</td>
<td style="text-align:center;">
19
</td>
</tr>
<tr>
<td style="text-align:center;">
105,599
</td>
<td style="text-align:center;">
e89eb1528cbb255f7a94ade170a93768
</td>
<td style="text-align:center;">
2,017
</td>
<td style="text-align:center;">
FRJA1**042015
</td>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
124,952
</td>
<td style="text-align:center;">
4e11314413f0172ea97c6926639bff6f
</td>
<td style="text-align:center;">
2,017
</td>
<td style="text-align:center;">
FRMU1**011996
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
23
</td>
</tr>
</tbody>
</table>
</div>
<p><br></p>
<p>Around 666 cases could change once dates are resolved with less than 18 years.</p>
</div>
<div id="see-here-for-duplicates-treatment." class="section level3">
<h3>See <a href="Duplicates.html">here</a> for duplicates treatment.</h3>
<hr />
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
